import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

const about = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>YouTube Playlist Duration Calculator</title>
      </Head>
      <main className={styles.main}>
        <h2>About page</h2>
      </main>
    </>
  );
};

export default about;
