import Head from "next/head";
import Image from "next/image";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>YouTube Playlist Duration Calculator</title>
      </Head>
      <Navbar />
      <main className={styles.main}>
        <div className={styles.container}>
          <div className={styles.form}>
            <input type="text" placeholder="youtube.com/playlist?list=ID" />
            <button type="button">Get Full Duration</button>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
